/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-tertiary-fixed": "#00210c",
              "primary-container": "#001f3f",
              "surface-container": "#efedf0",
              "surface-container-lowest": "#ffffff",
              "background": "#faf9fc",
              "on-primary-fixed": "#001c3a",
              "surface-container-highest": "#e3e2e5",
              "primary": "#1a2e4e",
              "on-secondary-container": "#6f5100",
              "outline": "#74777f",
              "tertiary-container": "#00250e",
              "on-primary": "#ffffff",
              "surface-bright": "#faf9fc",
              "on-primary-fixed-variant": "#2f486a",
              "secondary-container": "#daa520",
              "secondary-fixed": "#e8b63e",
              "on-background": "#1a1c1e",
              "on-tertiary-fixed-variant": "#005228",
              "error": "#ba1a1a",
              "tertiary-fixed": "#6bfe9c",
              "primary-fixed-dim": "#afc8f0",
              "on-tertiary-container": "#009b50",
              "surface-container-high": "#e9e7eb",
              "on-secondary": "#ffffff",
              "surface": "#faf9fc",
              "secondary": "#daa520",
              "surface-tint": "#476083",
              "on-primary-container": "#6f88ad",
              "outline-variant": "#c4c6cf",
              "inverse-surface": "#2f3033",
              "surface-container-low": "#f4f3f6",
              "on-secondary-fixed": "#ffffff",
              "secondary-fixed-dim": "#c29117",
              "surface-variant": "#e3e2e5",
              "on-surface": "#1a1c1e",
              "inverse-on-surface": "#f2f0f3",
              "on-surface-variant": "#43474e",
              "error-container": "#ffdad6",
              "on-error-container": "#93000a",
              "tertiary-fixed-dim": "#4ae183",
              "on-error": "#ffffff",
              "primary-fixed": "#d4e3ff",
              "on-secondary-fixed-variant": "#5c4300",
              "surface-dim": "#dbd9dd",
              "tertiary": "#000802",
              "inverse-primary": "#afc8f0",
              "on-tertiary": "#ffffff"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "stack-sm": "16px",
              "stack-md": "32px",
              "stack-lg": "64px",
              "section-padding": "80px",
              "base": "8px",
              "container-max": "1200px",
              "gutter": "24px"
      },
      "fontFamily": {
              "body-md": ["Inter", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "headline-md": ["Inter", "sans-serif"],
              "display-lg": ["Inter", "sans-serif"],
              "label-caps": ["Inter", "sans-serif"]
      },
      "fontSize": {
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
              "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-caps": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
